# Generated by Django 4.1.4 on 2023-02-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='choices',
        ),
        migrations.AddField(
            model_name='page',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.choice'),
        ),
    ]
