# Generated by Django 4.1.4 on 2023-02-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_page_choices_page_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='choices',
        ),
        migrations.AddField(
            model_name='page',
            name='choices',
            field=models.ManyToManyField(blank=True, null=True, to='book.choice'),
        ),
    ]
