# Generated by Django 4.1.4 on 2023-02-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_page_choices_page_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='redirect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='choices',
            field=models.ManyToManyField(blank=True, to='book.choice'),
        ),
    ]
